# Generated by Django 4.2.5 on 2023-10-13 05:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map_app", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="QuakeDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("event_id", models.IntegerField()),
                ("prefecture", models.CharField(max_length=100)),
                ("city", models.CharField(max_length=100)),
                ("intensity", models.CharField(max_length=100)),
                ("latitude", models.FloatField()),
                ("longitude", models.FloatField()),
            ],
        ),
    ]
