# Generated by Django 4.2.5 on 2023-10-13 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("map_app", "0002_quakedetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="quakelist",
            name="event_id",
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="quakedetail",
            name="event_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="map_app.quakelist"
            ),
        ),
    ]
