# Generated by Django 4.2.5 on 2023-10-16 07:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("map_app", "0005_alter_quakedetail_event_id"),
    ]

    operations = [
        migrations.CreateModel(
            name="CityList",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("city_code", models.CharField(max_length=100)),
                ("city_name", models.CharField(max_length=100)),
                ("prefecture_code", models.CharField(max_length=100)),
                ("prefecture_name", models.CharField(max_length=100)),
            ],
        ),
    ]
