# Generated by Django 4.2.5 on 2023-10-18 05:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("map_app", "0008_alter_quakedetail_event_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="addresslist",
            name="category",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.SET_DEFAULT,
                to="map_app.storelist",
            ),
        ),
    ]
